### ISSUE TITLE
Node::writeValueArray() compilation broken for std::vector<bool>

### ISSUE THREAD

**Issue by pemartin2** [open62541pp/open62541pp#550]
###Observed behavior
Node::writeValueArray() compilation broken for std::vector<bool> since c6fe48b. As for `std::vector<double>` everything is working fine thismight be related to std::vector<bool> being a special case. https://en.cppreference.com/w/cpp/container/vector_bool. However, I did not fully understand what is exactly happeing inside the templated code

### Steps to reproduce
use tests\node.cpp file and after
` Node varNode(connection, varId);`
insert 
```
    std::vector<bool> array{true, false};
    varNode.writeValueArray(array);
```
Building results in compilation error:

### Error message
```
C:\source\repos\open62541pp\include\open62541pp\types.hpp(1628): error C2440: '<function-style-cast>': cannot convert from 'initializer list' to 'opcua::Span<bool>'
  C:\source\repos\open62541pp\include\open62541pp/types.hpp(1628): note: 'opcua::Span<bool>::Span(std::initializer_list<bool>) noexcept': cannot convert argument 1 from 'initializer list' to 'std::initializer_list<bool>'
  C:\source\repos\open62541pp\include\open62541pp/types.hpp(1628): note: Element '1': no conversion from 'std::vector<bool,std::allocator<bool>>' to 'bool'
  C:\source\repos\open62541pp\include\open62541pp/types.hpp(1628): note: while trying to match the argument list '(initializer list)'
  C:\source\repos\open62541pp\include\open62541pp/types.hpp(1628): note: the template instantiation context (the oldest one first) is
  C:\source\repos\open62541pp\tests\node.cpp(12): note: see reference to function template instantiation 'void DOCTEST_ANON_TMP_20<Type>(void)' being compiled
          with
          [
              Type=opcua::Server
          ]
  C:\source\repos\open62541pp\tests\node.cpp(78): note: see reference to function template instantiation 'opcua::Node<opcua::Server> &opcua::Node<opcua::Server>::writeValueArray<std::vector<bool,std::allocator<bool>>>(const ArrayLike &)' being compiled
          with
          [
              ArrayLike=std::vector<bool,std::allocator<bool>>
          ]
  C:\source\repos\open62541pp\include\open62541pp/node.hpp(1183): note: see reference to function template instantiation 'opcua::Variant opcua::Variant::fromArray<opcua::VariantPolicy::Reference,std::vector<bool,std::allocator<bool>>&>(ArrayLike)' being compiled
          with
          [
              ArrayLike=std::vector<bool,std::allocator<bool>> &
          ]
  C:\source\repos\open62541pp\include\open62541pp/types.hpp(1142): note: see reference to function template instantiation 'opcua::Variant::Variant<std::vector<bool,std::allocator<bool>>&>(opcua::ReferenceTag,T)' being compiled
          with
          [
              T=std::vector<bool,std::allocator<bool>> &
          ]
  C:\source\repos\open62541pp\include\open62541pp/types.hpp(1086): note: see reference to function template instantiation 'void opcua::Variant::setValue<std::vector<bool,std::allocator<bool>>&>(T)' being compiled
          with
          [
              T=std::vector<bool,std::allocator<bool>> &
          ]
  C:\source\repos\open62541pp\include\open62541pp/types.hpp(1312): note: see reference to function template instantiation 'void opcua::Variant::setValueImpl<std::vector<bool,std::allocator<bool>>&,>(T)' being compiled
          with
          [
              T=std::vector<bool,std::allocator<bool>> &
          ]
C:\source\repos\open62541pp\include\open62541pp\types.hpp(1628): error C2672: 'opcua::Variant::setArray': no matching overloaded function found
  C:\source\repos\open62541pp\include\open62541pp/types.hpp(1394): note: could be 'void opcua::Variant::setArray(ArrayLike &&,const UA_DataType &) noexcept'
  C:\source\repos\open62541pp\include\open62541pp/types.hpp(1628): note: 'void opcua::Variant::setArray(ArrayLike &&,const UA_DataType &) noexcept': expects 2 arguments - 1 provided
  C:\source\repos\open62541pp\include\open62541pp/types.hpp(1382): note: or       'void opcua::Variant::setArray(ArrayLike &&) noexcept'
  [45/46] Building CXX object tests\CMakeFiles\open62541pp_tests.dir\services_monitoreditem.cpp.obj
```

**Comment by lukasberbuer** [comment]
Thanks for reporting this issue @pemartin2. Should be fixed with #553.
